#service.yaml

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8081       # expose port from the service
      targetPort: 8080 # the port where deployment is listening to
  type: NodePort


# kubectl get services
# minikube ip
# kubectl port-forward service/first-service 8081(expose port):8080(target port from the service)