#service.yaml

apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  selector:
    app: container-1
  ports:
    - protocol: TCP
      port: 8080       # expose port from the service
      targetPort: 8080 # the port where deployment is listening to
  type: NodePort



# kubectl get services
# minikube ip
# kubectl port-forward service/first-service 8080:8080